# Generated by Django 2.0.2 on 2018-07-02 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('account_pass', models.CharField(max_length=100)),
                ('account_taken_at', models.DateTimeField(verbose_name='Account in use since')),
                ('account_free', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_FirstName', models.CharField(max_length=100)),
                ('employee_LastName', models.CharField(max_length=100)),
                ('employee_ShortName', models.CharField(max_length=20)),
                ('employee_PersonalPhone', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='account_taken_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Employee'),
        ),
    ]
