# Generated by Django 2.0.2 on 2018-07-28 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['account_free', '-account_taken_at']},
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_PersonalEmail',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_taken_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Account in use since'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_taken_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_ShortName',
            field=models.CharField(blank=True, help_text='Your BB number', max_length=20),
        ),
    ]
