# Generated by Django 2.0.2 on 2018-07-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180729_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_status',
        ),
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(blank=True, choices=[('t', 'Taken'), ('a', 'Available'), ('m', 'Maintenance')], default='m', help_text='Account availability', max_length=1),
        ),
    ]
