# Generated by Django 2.0.2 on 2018-10-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180730_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('Safari', 'Safari'), ('Pluralsights', 'Pluralsights')], default='Safari', help_text='type', max_length=100),
        ),
    ]
