# Generated by Django 2.0.2 on 2018-10-02 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20181002_2359'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
